name: 'Test Net-SSLeay interactively'

on:
  push:
    branches:
      - master

jobs:
  shell:
    runs-on: macos-14
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
